export const context = {
  "@context": {
    "@version": 1.1,
    "id": "@id",
    "type": "@type",
    "@vocab": "http://www.w3.org/2004/02/skos/core#",
    "xsd": "http://www.w3.org/2001/XMLSchema#",
    "dct": "http://purl.org/dc/terms/",
    "owl": "http://www.w3.org/2002/07/owl#",
    "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
    "schema": "http://schema.org/",
    "vann": "http://purl.org/vocab/vann/",
    "vs": "https://www.w3.org/2003/06/sw-vocab-status/ns#",
    "title": { "@id": "dct:title", "@container": "@language" },
    "label": { "@id": "rdfs:label", "@container": "@language" },
    "description": { "@id": "dct:description", "@container": "@language" },
    "issued": { "@id": "dct:issued", "@type": "xsd:date" },
    "created": { "@id": "dct:created", "@type": "xsd:date" },
    "modified": { "@id": "dct:modified", "@type": "xsd:date" },
    "creator": "dct:creator",
    "contributor": "dct:contributor",
    "publisher": "dct:publisher",
    "license": { "@id": "dct:license" },
    "bibliographicCitation": "dct:bibliographicCitation",
    "preferredNamespacePrefix": "vann:preferredNamespacePrefix",
    "preferredNamespaceUri": "vann:preferredNamespaceUri",
    "isBasedOn": "schema:isBasedOn",
    "source": "dct:source",
    "seeAlso": "rdfs:seeAlso",
    "versionIRI": "owl:versionIRI",
    "versionInfo": "owl:versionInfo",
    "term_status": "vs:term_status",
    "hasTopConcept": { "@container": "@set" },
    "topConceptOf": { "@container": "@set" },
    "inScheme": { "@container": "@set" },
    "prefLabel": { "@container": "@language" },
    "altLabel": { "@container": ["@language", "@set"] },
    "definition": { "@container": "@language" },
    "scopeNote": { "@container": "@language" },
    "note": { "@container": "@language" },
    "notation": { "@container": "@set" },
    "example": { "@container": "@language" },
    "narrower": { "@container": "@set" },
    "related": { "@container": "@set" },
    "relatedMatch": { "@container": "@set" },
    "narrowerTransitive": { "@container": "@set" },
    "broaderTransitive": { "@container": "@set" },
    "broadMatch": { "@container": "@set" },
    "narrowMatch": { "@container": "@set" },
    "closeMatch": { "@container": "@set" },
    "exactMatch": { "@container": "@set" }
  }
}
